version: '3'
services:
  web:
    build: .
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
      - CACHE_PASSWORD=${CACHE_PASSWORD}
    depends_on:
      - db
      - cache
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  cache:
    image: redis:7.2.5-alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass $${CACHE_PASSWORD}"
    volumes:
      - cache:/data
    environment:
      - CACHE_PASSWORD=${CACHE_PASSWORD}
volumes:
  db_data:
  cache: